### PR TITLE
Upgrade Cli.Utils to preview4-004215

### PR DESCRIPTION
**Pull request by prafullbhosale**
cc @natemcmaster @pranavkm

### CODE REVIEW

**Comment by prafullbhosale** [comment]
For the RC.2 projects, the Msbuild referred by preview3 Cli.Utils package does not work. 
See aspnet/scaffolding/issues/350

**Comment by natemcmaster** [comment]
Which feed is this package on?

**Comment by prafullbhosale** [comment]
It is availabe on the [cli feed](https://dotnet.myget.org/feed/dotnet-cli)

**Comment by natemcmaster** [comment]
Ok cool. :shipit:

**Pull request merged**
