### PR TITLE
Update CPS packages with breaking changes

### PR DESCRIPTION
**Pull request by abpiskunov**
Update CPS packages with breaking changes

### CODE REVIEW

**Comment by abpiskunov** [comment]
@natemcmaster FYI

**Comment by abpiskunov** [comment]
Is master branch a correct branch for this change?

**Comment by natemcmaster** [comment]
Yes, master is the right branch.

**Comment by natemcmaster** [comment]
>  Unable to find package Microsoft.VisualStudio.ProjectSystem with version (>= 16.0.201-pre-g7d366164d0)

Build fails during NuGet restore. Where is this package found?

**Comment by natemcmaster** [comment]
Can you also change the VsixVersion to 16.0?

https://github.com/aspnet/DotNetTools/blob/9b598446caa060374081b27c00f4c357d064c680/version.props#L4

**Comment by abpiskunov** [comment]
Fixed and build passed

**Pull request merged**
